jupyterhub/ltiauthenticator

README.md

This PR contains instructions for getting Canvas and JupyterHub talking via `ltiauthenticator`. 
I have also introduced some changes to wording and explicit clarifications about some things that confused me when setting up authentication.

Canvas Implementation Instructions

---

README.md
ltiauthenticator/__init__.py

This PR is a simple patch to allow detection of the `canvas_custom_id` parameter in an LTI Launch Request. If the parameter is not detected, it will fall back to the `user_id` (lti user id) parameter. 
This is designed to authenticate users who are launching from a Canvas application running in public mode. A Canvas application running in anonymous mode will not send the `canvas_custom_id` parameter, and thus `user_id` will be used. 
A launch request from edX will also not contain the `canvas_custom_id` parameter, and thus fall back to `user_id`.
Note: This does not contain any tests. I was not sure the best way to write a test for `LTIAuthenticator.authenticate()`

Canvas ID Authentication

---

.travis.yml
setup.py

JupyterHub no longer supports 3.4 either.
This lets us use the `async def` syntax

Remove python 3.4 support

---

ltiauthenticator/__init__.py
setup.py
tests/test_lti.py

The dependency of oauthlib is too restrictive to work with JupyterHub
1.0.0 or at least the JupyterHub master.
```
ERROR: requests-oauthlib 1.2.0 has requirement oauthlib>=3.0.0, but you'll have oauthlib 2.1.0 which is incompatible.
ERROR: jupyterhub 1.0.1.dev0 has requirement oauthlib>=3.0, but you'll have oauthlib 2.1.0 which is incompatible.
```
oauthlib is used very limited in this package it seems, mainly regarding
a signature of some kind. The only import made from oauthlib is this
this:
```
from oauthlib.oauth1.rfc5849 import signature
```
The changelog:
https://github.com/oauthlib/oauthlib/blob/master/CHANGELOG.rst
But the changelog didn't capture all breaking changes, so i used git blame:
https://github.com/oauthlib/oauthlib/blame/master/oauthlib/oauth1/rfc5849/signature.py …

Bump oauthlib dependency

---

ltiauthenticator/__init__.py

This fixes #22 and is described in https://github.com/jupyterhub/ltiauthenticator/issues/22#issuecomment-562848326.

Fix typo - self.request should be handler.request

---

README.md

These are aligned with https://jupyterhub-team-compass.readthedocs.io/en/latest/building-blocks/readme-badges.html.

Add TravisCI and PyPI badges

---

.bumpversion.cfg
.travis.yml
RELEASE.md
dev-requirements.txt
ltiauthenticator/__init__.py
setup.py

I updated .travis.yml to include static code inspection. That made me raise a lot of questions regarding a code segment that may relate to #11.
PyPi: https://pypi.org/project/jupyterhub-ltiauthenticator/
TravisCI: https://travis-ci.org/jupyterhub/ltiauthenticator/settings

CI/CD update + a bug found by pytest-flakes?

---

ltiauthenticator/__init__.py

This PR is an attempt to fix the existing issue that is described here: 
https://github.com/jupyterhub/ltiauthenticator/issues/11
Also there is an existing opened PR for it
https://github.com/jupyterhub/ltiauthenticator/pull/16
But as far as I can see it is quite old, WIP and still opened 
**More in depth description:**
JupyterHub does not set cookies for users after log in if they were previously already set. Which results in situation when attempt of new user to log in via /hub/lti/launch will be discarded if he previously was already logged in under different account

Log out old user when new user logs in

---

.flake8
.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
dev-requirements.txt
ltiauthenticator/__init__.py
pyproject.yaml
tests/test_lti.py

- Adds Flake8 linter
- Adds black for code formatting
- Adds pre-commit config
- Adds Contributing guide
Related to #38 and #39

Add pre-commit and formatting tools

---

README.md
ltiauthenticator/lti11/auth.py
tests/conftest.py
tests/test_lti11_authenticator.py
tests/test_lti11_handlers.py

- Adds the `LTI11Authenticator.username_key` to set the username returned by the authenticator to something other than `custom_canvas_user_id` or `user_id` if specified
- Adds basic tests for `LTI11AuthenticateHandler` class
- Updates Readme
Continuation of #14
Closes #30 
cc/ @BenGig

Add username_key as an LTI 1.1 Authenticator configurable

---

ltiauthenticator/lti11/auth.py
tests/test_lti11_authenticator.py

- Updates the authenticator to remove HTTPError
- Pending: add test to assert that a missing `custom_canvas_user_id` uses the `user_id` value as a fallback.
Closes #50

Remove exception when default custom_canvas_user_id argument is not included in LTI 1.1 launch request

---

README.md
ltiauthenticator/__init__.py

Changed the configuration example, replaced the outdated `auth: type: "LTI"` configuration syntax.
I also included the `extraConfig` mentioned in #50.

README: updated k8s example

---

CHANGELOG.md

I created a changelog for 1.1.0 as because I read https://github.com/jupyterhub/ltiauthenticator/issues/53#issuecomment-898905140 suggesting a release was due.
@jgwerner, do you agree that there is no breaking change listed among the PRs in this changelog (so we don't bump the major version), and that there is some enhancements and not only bugfixes (so we bump the minor version rather than patch version)?

Add changelog for 1.1.0

---

CHANGELOG.md
CONTRIBUTING.md
README.md

- Updates helm chart configuration examples for both LTI 1.1 and LTI 1.3
- Fixes releases link in CONTRIBUTING.md
- Adds example to create a release with bump2version
Closes #72

Update helm chart examples

---

.pre-commit-config.yaml
docs/source/conf.py
examples/jupyterhub_config_lti11.py
examples/jupyterhub_config_lti13.py
ltiauthenticator/lti11/auth.py
ltiauthenticator/lti11/validator.py
ltiauthenticator/lti13/auth.py
ltiauthenticator/lti13/handlers.py
ltiauthenticator/lti13/validator.py
ltiauthenticator/tests/conftest.py
ltiauthenticator/tests/mocking.py
ltiauthenticator/tests/test_lti11_authenticator.py
ltiauthenticator/tests/test_lti11_handlers.py
ltiauthenticator/tests/test_lti13_authenticator.py
ltiauthenticator/tests/test_utils.py
ltiauthenticator/utils.py
pyproject.toml
setup.py

This aligns this repo with a practices across the JupyterHub ecosystem.

pre-commit: replace reorder-python-imports with isort

---

ltiauthenticator/lti13/validator.py
ltiauthenticator/tests/conftest.py
ltiauthenticator/utils.py
setup.py

@jgwerner this is my best attempt, but I can't verify this works and/or that I haven't broken something.
These breaking changes are changes that I've adjusted for in this PR.
- ![image](https://user-images.githubusercontent.com/3837114/171057515-29225f33-3cd5-450f-925f-a4527b751d09.png)
Because of this change in `jwt.encode()`, I've removed a call to [`<bytes>.decode()`](https://docs.python.org/3/library/stdtypes.html#bytes.decode) variable set by calling `jwt.encode()`, as that is now part of the `jwt.encode()` function.
- ![image](https://user-images.githubusercontent.com/3837114/171057558-347e5259-257d-4c85-aaaa-e64d12e1e5fd.png)
Because of this change in `jwt.decode()`, I've adjusted the arguments passed.
Closes #76.

breaking, maint: switch to using pyjwt v2

---

ltiauthenticator/lti13/auth.py
ltiauthenticator/lti13/handlers.py

This used to display information about the JupyterHub
in the LMS

LTI13: Make tool name & description configurable

---

README.md

When using `ltiauthenticator.LTIAuthenticator` as the authenticator class, the respective section in the `config.yml` must be named `LTIAuthenticator` for the traitlet system to work.
Alternatively, one could instead change to
```yml
JupyterHub:
authenticator_class: ltiauthenticator.lti11.auth.LTI11Authenticator
```
in the `config.yml` which would be analogous to the LTI1.3 configuration.

Fix documentation for LTI1.1

---

.pre-commit-config.yaml
ltiauthenticator/lti13/auth.py
ltiauthenticator/lti13/constants.py
ltiauthenticator/lti13/validator.py
tests/lti13/conftest.py
tests/lti13/test_lti13_validator.py

The validation of LTI 1.3 resource link launch requests is too strict. Actually all claims, required and optional, are currently mandatory. This strongly limits the usability of the authenticator since many LMS platforms might not or cannot provide all optional claims.
This PR limits the claims required for a valid launch request message to the [minimum defined by the LTI 1.3 specs](https://www.imsglobal.org/spec/lti/v1p3#required-message-claims).

Relax resource link launch request message requirements

---

ltiauthenticator/lti13/handlers.py

Since `LTI13LaunchValidator.validate_login_request` isn't returning a bool, the user agent is never redirected to the authorisation endpoint of the platform.

Fix login request validation

---

.pre-commit-config.yaml
ltiauthenticator/lti11/auth.py
ltiauthenticator/lti13/auth.py
ltiauthenticator/lti13/handlers.py
tests/lti11/test_lti11_authenticator.py
tests/lti13/mocking.py
tests/lti13/test_lti13_handlers.py

Currently, there is no route set to the OAuth2 login and callback handler in the LTI13Authenticator. This renders this authenticator essentially useless.
This PR adds routes to the respective handler. The paths are prefixed by `lti13` to avoid potential conflicts when using multiple authenticators become possible.
A backport of this fix for the most recent release would be great! If desired, I can open another PR for that.
Ref: #123

LTI13: Add missing oauth handler

---

ltiauthenticator/lti11/validator.py
tests/lti11/conftest.py

`oauthlib.oauth1.rfc5849.signature.sign_hmac_sha1` has been depricated. This function has been replaced by `oauthlib.oauth1.rfc5849.signature.sign_hmac_sha1_with_client`, which has slightly different signature.

Silence OAuthlib deprication warnings

---

docs/source/conf.py

`pydata-sphinx-theme==0.13.0` breaks rtd build. Instead of pinning the dependency, I have fixed the issue by providing the default value for `html_theme_options['icon_link']`. IMO, this should be the most maintainable solution.
Ref: https://github.com/pydata/pydata-sphinx-theme/issues/1220

docs: Fix read-the-docs build with pydata-sphinx-theme==0.13.0

---

ltiauthenticator/lti11/constants.py
ltiauthenticator/lti11/validator.py
tests/lti11/conftest.py
tests/lti11/test_lti11_validator.py

The `oauth_callback` parameter in the launch request is not required by LTI 1.1 and some tool consumer do not provide them in the request. According to th e[LTI 1.1 implementation notes](https://www.imsglobal.org/specs/ltiv1p1/implementation-guide#toc-4), setting a default value value is fine.
See #136

Lti 1.1 make oauth_callback optional

---

README.md
ltiauthenticator/lti13/auth.py
ltiauthenticator/lti13/constants.py
ltiauthenticator/lti13/error.py
ltiauthenticator/lti13/handlers.py
ltiauthenticator/lti13/validator.py
tests/lti13/test_lti13_authenticator.py
tests/lti13/test_lti13_handlers.py
tests/lti13/test_lti13_validator.py

If `username_key` is prefixed by "cutom_", the prefix will be removed and the key will be looked up in the `custom` claim of the ID token.

feat(lti13): Allow username key from custom claim

---

README.md
examples/jupyterhub_config_lti11.py

I found a small inconsistency in the README. AFAIK the authenticator class in the example at line 106 should be tiauthenticator.LTI11Authenticator, as in the note below the example.

Fix for inconsistency in README

---

CHANGELOG.md

This will prepare the next release for the ltiauthenticator reintroducing support for LTI 1.3. As a bonus, README.md is decluttered and much of its content is moved to https://ltiauthenticator.readthedocs.io.

Add changelog for 1.5.0

---

.github/dependabot.yml

This is one of several PRs opened in the juptyterhub github organization to systematically configure dependabot to update github actions on a monthly basis, for more information see https://github.com/jupyterhub/team-compass/issues/636.

dependabot: monthly updates of github actions

---

.github/dependabot.yaml

Followup to #148 and https://github.com/jupyterhub/team-compass/issues/636, as discussed in that issue.
> I [...] updated the PRs not merged with this rename when they were named .yml (~50% of the repos).
>
> There is no real benefit to having either .yaml or .yml, both works - I have a preference of sticking to one option, and preferably also with .yaml because thats what almost all other YAML files are in helm charts etc.

dependabot: rename to .yaml

---

docs/source/lti11/reference.md

Small Correction: ltiauthenticator.lti11.auth.LTI11Authenticator

docs(lti11): Fix typo in reference

---

ltiauthenticator/lti11/handlers.py
ltiauthenticator/lti13/handlers.py
pyproject.toml
tests/lti13/test_lti13_validator.py

JupyterHub 4.0.0 extended the verification of the _xsrf parameter in POST requests. But LTI requests do not include this parameter, and requests triggered the following error:
403: Forbidden '_xsrf' argument missing from POST
LTIAuthenticator thus was not compatible with JupyterHub 4.0.0. This PR resolves the issue for LTI 1.1 by ignoring the xsrf check; a similar change should be introduced for the LTI 1.3 authenticator.
See the tornado docs for more information on `check_xsrf_cookie`: https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.check_xsrf_cookie
Close #157.

fix: compatibility with XSRF check introduced in Jupyterhub 4.0.0

---

pyproject.toml

For some reason, the build process got broken. It seems to be required now to explicitly include the source directory since it is named differently than the package name which make the include heuristics of hatch to fail.

Fix build with hatchling backend

---

CHANGELOG.md

This includes self-merged one-line-prs to the github workflows #186 #187, and is motivated by the bugfix by @martinclaus in #185.

Add changelog for 1.6.2
